### ISSUE TITLE
zoom-area is not an known element

### ISSUE THREAD

**Issue by ericappcomm** [leonardosalles/ionic2-zoom-area#15]
I want  a image to be zoomed and scrollable (like <ion-scroll> in ionic2 )

'zoom-area' is not a known element:
1. If 'zoom-area' is an Angular component, then verify that it is part of this module.

package.json:
    "@angular/animations": "4.1.2",
    "ionic2-zoom-area": "^1.0.16",

app.module.ts:
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ZoomAreaModule } from 'ionic2-zoom-area';
[...]
imports: [
      BrowserAnimationsModule,
      ZoomAreaModule.forRoot()
[...]

places.html:
        <zoom-area>
		<img [src]="parent.imgBg" alt="zoom it" /> 
	</zoom-area>

Ionic 3: 3.20.0
cordova: 7.0.1

How to get this working?

**Comment by leonardosalles** [comment]
Probably you are importing the module at the wrong place, please check it again and the example app.

**Comment by gusreyes01** [comment]
I'm having the same issue with Ionic 3.

**Comment by tatianilima** [comment]
gureyes01 you need to import ZoomAreaModule in your shared module or child modules. I solved this question with this:

import { ZoomAreaModule } from 'ionic2-zoom-area';

@NgModule({
    ...
    imports: [
      ...
      ZoomAreaModule
    ],
    ...
})
export class SharedModule {}

**Comment by odortega** [comment]
This does worked for me with ionic 3

in add.module.ts
...
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
...

And then 

@NgModule({
    ...
providers:[
.
.
.
],
schemas: [CUSTOM_ELEMENTS_SCHEMA]
 ...
})
export class AppModule {}
