### ISSUE TITLE
Question: Possible to scroll to specific coordinates?

### ISSUE THREAD

**Issue by sgotre** [leonardosalles/ionic2-zoom-area#2]
Is it possible to scroll and scale to specific cooridnates?
Scaling seems to work, but how can i scroll to given parameters?

**Comment by leonardosalles** [comment]
It is not supported at this moment, will take a look on that feature ASAP.

**Comment by sgotre** [comment]
ok thank you for letting me know!
👍

**Comment by leonardosalles** [comment]
I will reopen until implement this feature. Working on that at this moment ;)

**Comment by leonardosalles** [comment]
@sgotre added this feature in 1.0.10, please update your lib version and follow the readme to the latest changes.
