### ISSUE TITLE
Failed launch ionic server

### ISSUE THREAD

**Issue by bogdanbaghiu** [leonardosalles/ionic2-zoom-area#20]
Hello. I'm imported you plugin but when I lauched ionic serve show me an error.

![image](https://user-images.githubusercontent.com/37840937/47561254-0bcb0900-d91b-11e8-870d-215df6eebd8b.png)

Problems is Subject Module.

**Comment by leonardosalles** [comment]
This problem is related to rxjs. Please check your version and use the same one that was used in example app.

**Comment by fcollombon** [comment]
This library is impossible to use if you fix the version of rxjs under v6. The actual version of angular required rxjs v6 or higher. 👍
