### ISSUE TITLE
Cannot find module "@angular/animations"

### ISSUE THREAD

**Issue by nibytes** [leonardosalles/ionic2-zoom-area#7]
Ionic 2/3
What info you need?
Stack:
`@http://localhost:8100/build/vendor.js:105178:7
__webpack_require__@http://localhost:8100/build/vendor.js:55:12
@http://localhost:8100/build/vendor.js:167148:79
__webpack_require__@http://localhost:8100/build/vendor.js:55:12
[297]@http://localhost:8100/build/main.js:713:76
__webpack_require__@http://localhost:8100/build/vendor.js:55:12
[292]@http://localhost:8100/build/main.js:672:70
__webpack_require__@http://localhost:8100/build/vendor.js:55:12
webpackJsonpCallback@http://localhost:8100/build/vendor.js:26:23
@http://localhost:8100/build/main.js:1:1
`
ionic info
cli packages: (C:\Users\username\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1

**Comment by nibytes** [comment]
if install animations to my project and add to @NgModule
`imports: [
    ...
    BrowserAnimationsModule,
    ...
  ],`
all work

**Comment by leonardosalles** [comment]
It should be already included on the project, will investigate.

**Comment by nibytes** [comment]
I think it need add to readme
