### ISSUE TITLE
Error: StaticInjectorError[ZoomAreaProvider]

### ISSUE THREAD

**Issue by big-r81** [leonardosalles/ionic2-zoom-area#8]
Hi,

after fixing #6 I'm getting the following error:
```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[ZoomAreaProvider]: 
  StaticInjectorError[ZoomAreaProvider]: 
    NullInjectorError: No provider for ZoomAreaProvider!
Error: StaticInjectorError[ZoomAreaProvider]: 
  StaticInjectorError[ZoomAreaProvider]: 
    NullInjectorError: No provider for ZoomAreaProvider!
...
```

If this component is lazy loaded, shouldn't the provider be in the NgModule declaration
in _zoom-area.module.ts_? You defined it in the forRoot() method...

**Comment by leonardosalles** [comment]
1.0.11 added to npm, example app was updated too, LazyLoading is working perfectly right now. Thanks for your help and for good issues 😜
